In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from astropy import units as u, constants as const
from astropy.units import Quantity

In [2]:
df = pd.read_csv("solar_system.csv")

# display(df)

print("---Original---")
print(df.shape, df.shape[0], df.shape[1])

df = df.set_index("Attribute").T #make attribute column the index and transpose the table so that planets = rows and attr = cols
df.index.name = "Planet" #rename index to Planet
df.reset_index(inplace=True) #Move the index back into a column
df.columns.name = None #Remove column index name

print("---Transposed---")
print(df.shape, df.shape[0], df.shape[1])
print(df.columns.tolist())
cols_w_units = [c for c in df.columns if "(" in c and ")" in c]
cols_wo_units = [c for c in df.columns if c not in cols_w_units]
print(len(cols_w_units), cols_w_units)
print(len(cols_wo_units), cols_wo_units)

display(df)

'''
the new shape isnt 11,20 becuase we dont have 11 attr and 20 planets. we have 10 planets (or really objects), and 21 attrs
'''

---Original---
(20, 11) 20 11
---Transposed---
(10, 21) 10 21
['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']
16 ['Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)']
5 ['Planet', 'Orbital Eccentricity', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

'\nthe new shape isnt 11,20 becuase we dont have 11 attr and 20 planets. we have 10 planets (or really objects), and 21 attrs\n'

In [3]:
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [4]:
for col in df.columns:
    print(col, df[col].apply(type).unique())

'''
the actual values are of class str, this is problematic because we cannot perform mathematics on them and cannot be plotted/performed operations...etc
'''

Planet [<class 'str'>]
Mass (10^24kg) [<class 'str'>]
Diameter (km) [<class 'str'>]
Density (kg/m^3) [<class 'str'>]
Gravity (m/s^2) [<class 'str'>]
Escape Velocity (km/s) [<class 'str'>]
Rotation Period (hours) [<class 'str'>]
Length of Day (hours) [<class 'str'>]
Distance from Sun (10^6 km) [<class 'str'>]
Perihelion (10^6 km) [<class 'str'>]
Aphelion (10^6 km) [<class 'str'>]
Orbital Period (days) [<class 'str'>]
Orbital Velocity (km/s) [<class 'str'>]
Orbital Inclination (deg) [<class 'str'>]
Orbital Eccentricity [<class 'str'>]
Obliquity to Orbit (deg) [<class 'str'>]
Mean Temperature (C) [<class 'str'>]
Surface Pressure (bars) [<class 'str'>]
Number of Moons [<class 'str'>]
Ring System? [<class 'str'>]
Global Magnetic Field? [<class 'str'>]

'\nthe actual values are of class str, this is problematic because we cannot perform mathematics on them and cannot be plotted/performed operations...etc\n'

In [5]:
for col in df.columns:
    if col not in ["Planet", "Ring System?", "Global Magnetic Field?"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

df.dtypes

'''
now we have float64-all numerical with decimalcolumns, int64-numerical without decimal points, and object-categorical/string columns.
columns such as planet, global mag field, and ring system, are objects, because they need to be described w actual words
'''

'\nnow we have float64-all numerical with decimalcolumns, int64-numerical without decimal points, and object-categorical/string columns.\ncolumns such as planet, global mag field, and ring system, are objects, because they need to be described w actual words\n'

In [6]:
display(df)

def attach_units(col, unit, new_col):
    new_values = []
    for val in df[col]:
        new_values.append(val * unit)   
    df[col] = new_values
    df.rename(columns={col: new_col}, inplace=True)

attach_units(
    col="Mass (10^24kg)",
    unit=1e24 * u.kg,
    new_col="Mass (kg)"
)

print(df["Mass (kg)"])

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.900,46.000,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108.200,107.500,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149.600,147.100,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.000,206.700,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778.500,740.600,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432.000,1357.600,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867.000,2732.700,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515.000,4471.100,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906.400,4436.800,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

0                   3.3e+23 kg
1                  4.87e+24 kg
2     5.969999999999999e+24 kg
3                   7.3e+22 kg
4                  6.42e+23 kg
5                 1.898e+27 kg
6                  5.68e+26 kg
7                  8.68e+25 kg
8    1.0199999999999999e+26 kg
9                   1.3e+22 kg
Name: Mass (kg), dtype: object

In [7]:
attach_units("Perihelion (10^6 km)", 1e7 * u.km, "Perihelion (km)")
attach_units("Aphelion (10^6 km)", 1e7 * u.km, "Aphelion (km)")


smaj = (df["Perihelion (km)"] + df["Aphelion (km)"]) / 2


pos = df.columns.get_loc("Aphelion (km)") + 1
df.insert(pos, "Semi-Major Axis (km)", smaj)

print(df.columns)
print(df["Semi-Major Axis (km)"])

display(df)

Index(['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (km)', 'Aphelion (km)', 'Semi-Major Axis (km)',
       'Orbital Period (days)', 'Orbital Velocity (km/s)',
       'Orbital Inclination (deg)', 'Orbital Eccentricity',
       'Obliquity to Orbit (deg)', 'Mean Temperature (C)',
       'Surface Pressure (bars)', 'Number of Moons', 'Ring System?',
       'Global Magnetic Field?'],
      dtype='object')
0      579000000.0 km
1     1082000000.0 km
2     1496000000.0 km
3        3845000.0 km
4     2280000000.0 km
5     7785000000.0 km
6    14320500000.0 km
7    28670500000.0 km
8    45150000000.0 km
9    59063500000.0 km
Name: Semi-Major Axis (km), dtype: object

,Planet,Mass (kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,3.3e+23 kg,4879,5429,3.7,4.3,1407.6,4222.6,57.900,460000000.0 km,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.87e+24 kg,12104,5243,8.9,10.4,-5832.5,2802.0,108.200,1075000000.0 km,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.969999999999999e+24 kg,12756,5514,9.8,11.2,23.9,24.0,149.600,1471000000.0 km,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,7.3e+22 kg,3475,3340,1.6,2.4,655.7,708.7,0.384,3630000.0 km,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,6.42e+23 kg,6792,3934,3.7,5.0,24.6,24.7,228.000,2067000000.0 km,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1.898e+27 kg,142984,1326,23.1,59.5,9.9,9.9,778.500,7406000000.0 km,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,5.68e+26 kg,120536,687,9.0,35.5,10.7,10.7,1432.000,13576000000.0 km,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,8.68e+25 kg,51118,1270,8.7,21.3,-17.2,17.2,2867.000,27327000000.0 km,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,1.0199999999999999e+26 kg,49528,1638,11.0,23.5,16.1,16.1,4515.000,44711000000.0 km,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,1.3e+22 kg,2376,1850,0.7,1.3,-153.3,153.3,5906.400,44368000000.0 km,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

In [8]:
display(df)
print(df['Semi-Major Axis (km)'])

,Planet,Mass (kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,3.3e+23 kg,4879,5429,3.7,4.3,1407.6,4222.6,57.900,460000000.0 km,...,88.0,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes
1,Venus,4.87e+24 kg,12104,5243,8.9,10.4,-5832.5,2802.0,108.200,1075000000.0 km,...,224.7,35.0,3.4,0.007,177.400,464,92.00000,0,No,No
2,Earth,5.969999999999999e+24 kg,12756,5514,9.8,11.2,23.9,24.0,149.600,1471000000.0 km,...,365.2,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes
3,Moon,7.3e+22 kg,3475,3340,1.6,2.4,655.7,708.7,0.384,3630000.0 km,...,27.3,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No
4,Mars,6.42e+23 kg,6792,3934,3.7,5.0,24.6,24.7,228.000,2067000000.0 km,...,687.0,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No
5,Jupiter,1.898e+27 kg,142984,1326,23.1,59.5,9.9,9.9,778.500,7406000000.0 km,...,4331.0,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes
6,Saturn,5.68e+26 kg,120536,687,9.0,35.5,10.7,10.7,1432.000,13576000000.0 km,...,10747.0,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes
7,Uranus,8.68e+25 kg,51118,1270,8.7,21.3,-17.2,17.2,2867.000,27327000000.0 km,...,30589.0,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes
8,Neptune,1.0199999999999999e+26 kg,49528,1638,11.0,23.5,16.1,16.1,4515.000,44711000000.0 km,...,59800.0,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes
9,Pluto,1.3e+22 kg,2376,1850,0.7,1.3,-153.3,153.3,5906.400,44368000000.0 km,...,90560.0,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown

0      579000000.0 km
1     1082000000.0 km
2     1496000000.0 km
3        3845000.0 km
4     2280000000.0 km
5     7785000000.0 km
6    14320500000.0 km
7    28670500000.0 km
8    45150000000.0 km
9    59063500000.0 km
Name: Semi-Major Axis (km), dtype: object

In [9]:
print(df.columns.tolist())
print(df["Orbital Period (days)"].head())
print(type(df["Orbital Period (days)"].iloc[0]))

['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (km)', 'Aphelion (km)', 'Semi-Major Axis (km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']
0     88.0
1    224.7
2    365.2
3     27.3
4    687.0
Name: Orbital Period (days), dtype: float64
<class 'numpy.float64'>

In [10]:
attach_units("Orbital Period (days)", 1 * u.year, "Orbital Period (years)")

In [11]:
'''
AU: distance from earth to the sun
'''

print(const.au)
print(const.au.to(u.km))

  Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2
149597870.70000002 km

In [12]:
dist_cols = [
    "Diameter (km)",
    "Perihelion (km)",
    "Aphelion (km)",
    "Semi-Major Axis (km)"
]

km_to_au = 1 / 149597870.7  

for col in dist_cols:
    km_vals = df[col]                         
    au_vals = km_vals * km_to_au                 
    new_col = col.replace("(km)", "(AU)")
    df[new_col] = au_vals

'''i could not get it to change the units with the .to method,
for some reason, it always returned an error such as 
AttributeError: 'Series' object has no attribute 'to'
and I could not get it to work after some reseach online as well'''

"i could not get it to change the units with the .to method,\nfor some reason, it always returned an error such as \nAttributeError: 'Series' object has no attribute 'to'\nand I could not get it to work after some reseach online as well"

In [13]:
df.to_csv("units.csv", index=False)